/** Full timeline step bodies in all UI languages (titles still from i18n timeline.timelineTitles). */

const en = [
  { expl: 'Confirm your country of birth is eligible for the current program year using official State Department instructions.', warn: 'Eligibility is based on country of birth, not current nationality alone.', remind: 'Review the official country eligibility list each year; it can change.' },
  { expl: 'Prepare a compliant digital photo that meets strict composition, size, and background rules.', warn: 'Non-compliant photos are a leading reason for disqualification.', remind: 'Do not use filters, heavy retouching, or old photos that no longer match your appearance.' },
  { expl: 'Submit your entry only during the official registration window on the authorized U.S. government site.', warn: 'Multiple entries for the same person typically disqualify the applicant.', remind: 'Entry is free; avoid any site that charges a fee for “registration.”' },
  { expl: 'Store your confirmation number securely; you need it to check results and for future reference.', warn: 'Lost confirmation numbers can prevent you from checking status.', remind: 'Save a screenshot and a backup in a password manager or secure file.' },
  { expl: 'Check results only through the official Entrant Status Check system for the correct program year.', warn: 'Ignore unofficial emails or messages claiming you were selected.', remind: 'Selection is never communicated only by phone or random social media.' },
  { expl: 'If selected, learn how to read your case number and what it implies for processing order.', warn: 'Case numbers relate to regional quotas and visa bulletin movement.', remind: 'Track monthly Visa Bulletins to understand when your number may become current.' },
  { expl: 'Complete the DS-260 immigrant visa application online with accurate, consistent information.', warn: 'Inconsistencies with passports and civil documents can cause delays or denials.', remind: 'Review every page before submission; print or save the confirmation.' },
  { expl: 'Gather civil documents per reciprocity schedules and embassy instructions for your nationality and history.', warn: 'Wrong or incomplete documents are a common interview issue.', remind: 'Obtain certified copies and certified translations where required.' },
  { expl: 'Monitor the Visa Bulletin to know when your case may proceed to interview scheduling.', warn: 'Being “selected” does not guarantee a visa if numbers exhaust before your case is processed.', remind: 'Understand cut-off numbers for your region and plan finances and timelines carefully.' },
  { expl: 'Complete the medical exam only with a panel physician authorized by the embassy.', warn: 'Exams from non-panel doctors are not accepted.', remind: 'Bring vaccination records and passport; follow pre-exam instructions.' },
  { expl: 'Attend the embassy interview on time with originals, copies, and organized binders as instructed.', warn: 'Prohibited items and security rules vary by post—check official notices.', remind: 'Answer clearly and truthfully; bring evidence that supports your DS-260 answers.' },
  { expl: 'You may receive approval, administrative processing, or refusal; each has different next steps.', warn: 'Do not book non-refundable travel until you have the visa in hand.', remind: 'Administrative processing timelines are unpredictable—plan accordingly.' },
  { expl: 'If instructed, pay the USCIS immigrant fee online before travel when applicable to your case.', warn: 'Payment instructions come from official sources—verify URLs carefully.', remind: 'Keep payment receipts with your immigration records.' },
  { expl: 'Book travel only after visa issuance and understand first-entry and passport validity requirements.', warn: 'Visas have validity windows; entry after expiration is not allowed.', remind: 'Carry sealed visa packet instructions if provided; do not open immigration envelopes if marked sealed.' },
  { expl: 'After admission, apply for a Social Security number if eligible and as directed on arrival materials.', warn: 'Processing times vary; protect your SSN once issued.', remind: 'Update your address with USCIS if you move after arrival.' },
  { expl: 'Your physical green card may arrive by mail after you pay fees and complete processing steps.', warn: 'Report non-delivery through official USCIS channels.', remind: 'Ensure the mailing address on file is accurate and secure.' },
  { expl: 'Build housing, employment, banking, and community foundations for long-term stability.', warn: 'Avoid predatory loans and unauthorized “immigration help” that promises shortcuts.', remind: 'Use official government portals and reputable community organizations.' },
]

const fr = [
  { expl: 'Vérifiez l’éligibilité de votre pays de naissance pour l’année du programme selon les instructions officielles du Département d’État.', warn: 'L’éligibilité repose sur le pays de naissance, pas seulement sur la nationalité actuelle.', remind: 'Consultez chaque année la liste officielle des pays éligibles : elle peut changer.' },
  { expl: 'Préparez une photo numérique conforme (cadrage, taille, arrière-plan) selon les règles officielles.', warn: 'Les photos non conformes sont une cause fréquente de disqualification.', remind: 'Pas de filtres ni retouches excessives ; évitez les photos trop anciennes.' },
  { expl: 'Soumettez votre participation uniquement pendant la période officielle sur le site gouvernemental autorisé.', warn: 'Plusieurs participations pour la même personne entraînent en général la disqualification.', remind: 'La participation est gratuite ; méfiez-vous des sites payants pour “s’inscrire”.' },
  { expl: 'Conservez précieusement votre numéro de confirmation pour vérifier les résultats et vos dossiers futurs.', warn: 'Sans numéro de confirmation, vous risquez de ne pas pouvoir consulter votre statut.', remind: 'Enregistrez une capture d’écran et une copie dans un gestionnaire de mots de passe sécurisé.' },
  { expl: 'Consultez les résultats uniquement via le système officiel Entrant Status Check pour la bonne année de programme.', warn: 'Ignorez les e-mails ou messages non officiels annonçant une sélection.', remind: 'La sélection n’est jamais communiquée uniquement par téléphone ou réseaux sociaux aléatoires.' },
  { expl: 'Si vous êtes sélectionné, comprenez la lecture du numéro de dossier et son impact sur l’ordre de traitement.', warn: 'Les numéros de dossier sont liés aux quotas régionaux et au Visa Bulletin.', remind: 'Suivez chaque mois le Visa Bulletin pour savoir quand votre numéro peut devenir “current”.' },
  { expl: 'Complétez le DS-260 en ligne avec des informations exactes et cohérentes.', warn: 'Les incohérences avec passeport et documents civils peuvent retarder ou faire refuser le visa.', remind: 'Relisez chaque page avant envoi ; imprimez ou enregistrez la confirmation.' },
  { expl: 'Rassemblez les documents civils selon les tableaux de réciprocité et les instructions de l’ambassade.', warn: 'Documents incomplets ou erronés : problème fréquent à l’entretien.', remind: 'Obtenez des copies certifiées et des traductions assermentées si requis.' },
  { expl: 'Surveillez le Visa Bulletin pour savoir quand votre dossier peut avancer vers l’entretien.', warn: 'Être sélectionné ne garantit pas un visa si les numéros s’épuisent avant votre traitement.', remind: 'Comprenez les dates limites par région et planifiez budget et calendrier.' },
  { expl: 'Passez l’examen médical uniquement chez un médecin panéliste agréé par l’ambassade.', warn: 'Les examens réalisés hors réseau panéliste ne sont pas acceptés.', remind: 'Apportez carnet de vaccination et passeport ; suivez les consignes pré-examen.' },
  { expl: 'Présentez-vous à l’heure à l’entretien avec originaux, copies et classeur organisé comme demandé.', warn: 'Objets interdits et règles de sécurité varient selon le poste — lisez les avis officiels.', remind: 'Répondez clairement et honnêtement ; apportez des preuves cohérentes avec le DS-260.' },
  { expl: 'Vous pouvez recevoir une approbation, un traitement administratif ou un refus — suites différentes.', warn: 'N’achetez pas de voyage non remboursable tant que le visa n’est pas en main.', remind: 'Les délais de traitement administratif sont imprévisibles.' },
  { expl: 'Si requis, payez en ligne les frais d’immigrant USCIS avant le voyage selon votre cas.', warn: 'Les instructions de paiement viennent de sources officielles — vérifiez l’URL.', remind: 'Conservez les reçus avec vos dossiers d’immigration.' },
  { expl: 'Réservez un voyage seulement après délivrance du visa et vérifiez validité du passeport et fenêtre du visa.', warn: 'Les visas ont une période de validité ; entrée après expiration impossible.', remind: 'Si un pli scellé vous est remis, respectez les consignes “ne pas ouvrir” si indiqué.' },
  { expl: 'Après l’admission, demandez un numéro de sécurité sociale si vous y êtes éligible, selon les documents d’arrivée.', warn: 'Les délais varient ; protégez votre SSN une fois délivré.', remind: 'Mettez à jour votre adresse auprès de l’USCIS en cas de déménagement.' },
  { expl: 'La carte verte physique peut arriver par courrier après paiement des frais et étapes requises.', warn: 'Signalez une non-réception via les canaux officiels USCIS.', remind: 'Vérifiez que l’adresse postale en dossier est exacte et sécurisée.' },
  { expl: 'Construisez logement, emploi, banque et réseau pour une stabilité à long terme.', warn: 'Évitez crédits abusifs et “aides” non autorisées promettant des raccourcis.', remind: 'Privilégiez les portails gouvernementaux et associations fiables.' },
]

const es = [
  { expl: 'Confirme la elegibilidad de su país de nacimiento para el año del programa según las instrucciones oficiales del Departamento de Estado.', warn: 'La elegibilidad se basa en el país de nacimiento, no solo en la nacionalidad actual.', remind: 'Revise cada año la lista oficial de países elegibles; puede cambiar.' },
  { expl: 'Prepare una foto digital conforme (encuadre, tamaño, fondo) según las reglas oficiales.', warn: 'Las fotos no conformes son una causa frecuente de descalificación.', remind: 'No use filtros ni retoques fuertes; evite fotos antiguas que ya no se parezcan a usted.' },
  { expl: 'Envíe su participación solo en la ventana oficial y en el sitio gubernamental autorizado.', warn: 'Varias participaciones de la mis persona suelen descalificar.', remind: 'La participación es gratuita; evite sitios que cobran por “registro”.' },
  { expl: 'Guarde de forma segura su número de confirmación para consultar resultados y trámites futuros.', warn: 'Sin número de confirmación puede no poder verificar su estado.', remind: 'Guarde captura de pantalla y copia en un gestor de contraseñas seguro.' },
  { expl: 'Consulte resultados solo en el Entrant Status Check oficial del año correcto.', warn: 'Ignore correos o mensajes no oficiales que digan que fue seleccionado.', remind: 'La selección no se comunica solo por teléfono o redes sociales al azar.' },
  { expl: 'Si es seleccionado, entienda su número de caso y qué implica para el orden de procesamiento.', warn: 'Los números de caso se relacionan con cupos regionales y el Visa Bulletin.', remind: 'Siga el Visa Bulletin mensual para saber cuándo su número puede estar “current”.' },
  { expl: 'Complete el DS-260 en línea con información precisa y coherente.', warn: 'Incoherencias con pasaporte y documentos civiles pueden causar demoras o denegación.', remind: 'Revise cada pantalla antes de enviar; imprima o guarde la confirmación.' },
  { expl: 'Reúna documentos civiles según reciprocidad e instrucciones de la embajada.', warn: 'Documentos incorrectos o incompletos son un problema frecuente en la entrevista.', remind: 'Obtenga copias certificadas y traducciones juradas si se exigen.' },
  { expl: 'Monitoree el Visa Bulletin para saber cuándo su caso puede avanzar a cita de entrevista.', warn: 'Ser seleccionado no garantiza visa si los números se agotan antes de su turno.', remind: 'Entienda los números de corte por región y planifique tiempo y dinero.' },
  { expl: 'Complete el examen médico solo con un médico de panel autorizado por la embajada.', warn: 'No se aceptan exámenes de médicos no autorizados.', remind: 'Lleve vacunas y pasaporte; siga instrucciones previas al examen.' },
  { expl: 'Asista a la entrevista a tiempo con originales, copias y carpeta ordenada según indicaciones.', warn: 'Objetos prohibidos y seguridad varían por sede — revise avisos oficiales.', remind: 'Responda con claridad y verdad; lleve evidencia coherente con el DS-260.' },
  { expl: 'Puede recibir aprobación, procesamiento administrativo o negación; cada uno tiene pasos distintos.', warn: 'No reserve viajes no reembolsables hasta tener el visa en mano.', remind: 'Los tiempos de procesamiento administrativo son impredecibles.' },
  { expl: 'Si corresponde, pague en línea la tarifa de inmigrante USCIS antes de viajar.', warn: 'Las instrucciones de pago vienen de fuentes oficiales — verifique la URL.', remind: 'Guarde recibidos con su expediente migratorio.' },
  { expl: 'Reserve viaje solo después de la emisión del visa y revise validez del pasaporte y ventana del visa.', warn: 'Los visados tienen vigencia; no puede entrar después de vencidos.', remind: 'Si recibe sobre sellado, siga instrucciones de no abrir si aplica.' },
  { expl: 'Tras el ingreso, solicite SSN si es elegible según materiales de llegada.', warn: 'Los plazos varían; proteja su SSN una vez emitido.', remind: 'Actualice su dirección en USCIS si se muda.' },
  { expl: 'La tarjeta verde física puede llegar por correo tras pagos y pasos requeridos.', warn: 'Reporte no entrega por canales oficiales USCIS.', remind: 'Confirme que la dirección postal sea correcta y segura.' },
  { expl: 'Construya vivienda, empleo, banca y comunidad para estabilidad a largo plazo.', warn: 'Evite préstamos abusivos y “ayudas” no autorizadas que prometen atajos.', remind: 'Use portales oficiales y organizaciones confiables.' },
]

const ar = [
  { expl: 'تحقق من أهلية بلد الميلاد للسنة الحالية وفق تعليمات وزارة الخارجية الأمريكية الرسمية.', warn: 'الأهلية تعتمد على بلد الميلاد وليس الجنسية الحالية وحدها.', remind: 'راجع قائمة الأهلية الرسمية كل سنة لأنها قد تتغير.' },
  { expl: 'جهّز صورة رقمية مطابقة للمعايير (الإطار، الحجم، الخلفية) حسب القواعد الرسمية.', warn: 'الصور غير المطابقة من أسباب الاستبعاد الشائعة.', remind: 'تجنب الفلاتر والتعديل المفرط والصور القديمة التي لا تشبه ملامحك الحالية.' },
  { expl: 'قدّم المشاركة فقط خلال النافذة الرسمية على الموقع الحكومي المصرّح به.', warn: 'تقديم أكثر من مشاركة لنفس الشخص عادة يؤدي للاستبعاد.', remind: 'المشاركة مجانية؛ تجنب المواقع التي تطلب رسوم «تسجيل».' },
  { expl: 'احفظ رقم التأكيد بأمان؛ تحتاجه للنتائج وللمراجعة لاحقًا.', warn: 'فقدان رقم التأكيد قد يمنعك من التحقق من الحالة.', remind: 'احفظ لقطة شاشة ونسخة احتياطية في مدير كلمات مرور آمن.' },
  { expl: 'تحقق من النتائج فقط عبر نظام التحقق من حالة المشارك الرسمي للسنة الصحيحة.', warn: 'تجاهل رسائل البريد أو الوسائط غير الرسمية التي تدّعي الاختيار.', remind: 'لا يُعلَن الاختيار عبر هاتف أو وسائل اجتماعية عشوائية فقط.' },
  { expl: 'إذا اُخترتَ، افهم رقم الحالة ومعنى ترتيب المعالجة.', warn: 'أرقام الحالات مرتبطة بحصص إقليمية وحركة نشرة التأشيرات.', remind: 'تابع نشرة التأشيرات الشهرية لمعرفة متى قد يصبح رقمك حاليًا.' },
  { expl: 'أكمل DS-260 عبر الإنترنت بمعلومات دقيقة ومتسقة.', warn: 'التناقض مع جواز السفر والوثائق المدنية قد يسبب تأخيرًا أو رفضًا.', remind: 'راجع كل صفحة قبل الإرسال؛ اطبع أو احفظ صفحة التأكيد.' },
  { expl: 'اجمع الوثائق المدنية وفق جداول المعاملة بالمثل وتعليمات السفارة.', warn: 'الوثائق الخاطئة أو الناقصة مشكلة شائعة في المقابلة.', remind: 'احصل على نسخ مصدّقة وترجمات معتمدة عند الحاجة.' },
  { expl: 'راقب نشرة التأشيرات لمعرفة متى يمكن جدولة مقابلتك.', warn: 'الاختيار لا يضمن تأشيرة إذا نفدت الأرقام قبل معالجة ملفك.', remind: 'افهم أرقام القطع لمنطقتك وخطط للمال والوقت.' },
  { expl: 'أكمل الفحص الطبي فقط لدى طبيب لوحة معتمد من السفارة.', warn: 'لا تُقبل فحوصات أطباء غير معتمدين.', remind: 'أحضر سجل التطعيم والجواز؛ اتبع تعليمات ما قبل الفحص.' },
  { expl: 'احضر المقابلة في الوقت مع الأصول والنسخ والملف المنظم كما طُلب.', warn: 'تختلف الممنوعات وقواعد الأمن حسب البعثة — راجع الإشعارات الرسمية.', remind: 'أجب بوضوح وأمانة؛ أحضر أدلة تدعم إجابات DS-260.' },
  { expl: 'قد تحصل على موافقة أو معالجة إدارية أو رفض؛ لكل حالة خطوات مختلفة.', warn: 'لا تحجز سفرًا غير قابل للاسترداد قبل استلام التأشيرة.', remind: 'مدد المعالجة الإدارية غير متوقعة.' },
  { expl: 'إذا طُلب منك، ادفع رسوم المهاجر USCIS عبر الإنترنت قبل السفر عند انطباق ذلك.', warn: 'تعليمات الدفع من مصادر رسمية — تحقق من عنوان الموقع.', remind: 'احتفظ بإيصالات الدفع مع ملفات الهجرة.' },
  { expl: 'احجز السفر بعد إصدار التأشيرة وتأكد من صلاحية الجواز ونافذة الدخول.', warn: 'للتأشيرات فترة صلاحية؛ لا يُسمح بالدخول بعد انتهائها.', remind: 'إذا وُزِع ظرف مختوم، اتبع تعليمات «لا تفتح» إن وُجدت.' },
  { expl: 'بعد القبول، تقدّم لرقم الضمان الاجتماعي إن كنت مؤهلاً حسب مواد الوصول.', warn: 'تختلف المدد؛ احمِ رقمك بعد الإصدار.', remind: 'حدّث عنوانك لدى USCIS عند الانتقال.' },
  { expl: 'قد تصل البطاقة الخضراء بالبريد بعد الدفع وإكمال الخطوات.', warn: 'بلّغ عدم التسليم عبر قنوات USCIS الرسمية.', remind: 'تأكد أن عنوان البريد دقيق وآمن.' },
  { expl: 'ابنِ السكن والعمل والمصرف والمجتمع لاستقرار طويل الأمد.', warn: 'تجنب القروض المفترسة و«مساعدة هجرة» غير مرخّصة.', remind: 'استخدم البوابات الحكومية والجمعيات الموثوقة.' },
]

export const timelineDetailsByLang = { en, fr, es, ar }

export function timelineStepsFor(lang) {
  const list = timelineDetailsByLang[lang] || timelineDetailsByLang.en
  return list.length ? list : timelineDetailsByLang.en
}
